### ISSUE TITLE
Math.random

### ISSUE THREAD

**Issue by EliasSalom** [Fullstack-Alfanar/malek-s-homework#1]
https://github.com/Fullstack-Alfanar/malek-s-homework/blob/ac9e1440c185dcfe0944d9ee8d3956403b81b49b/js/jas.js#L47

when I asked for a random number, I mean to write some random number, not to use `Math.random`
and because you have been using it, I need to be sure,  
### Are you know how to use it ?!

**Comment by MalekSafory** [comment]
yes i know i have learned it before
